---
- hosts: linux
  become: true

  tasks:

  - name: Actualizo todos los paquetes instalados CentOS
    ansible.builtin.dnf:
      name: "*"
      state: latest
    notify: Reiniciar servidores
    when: ansible_os_family == "RedHat"

  - name: Actualizo todos los paquetes instalados Ubuntu
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
    notify: Reiniciar servidores
    when: ansible_os_family == "Debian"

  handlers:

  - name: Reiniciar servidores
    ansible.builtin.reboot:
