---
- hosts: linux 
  become: true

  tasks:

  - name: Add PermitRootLogin line
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: "^#PermitRootLogin"
      line: "PermitRootLogin no"
    notify: Systemd reboot

  handlers:

  - name: Systemd reboot
    ansible.builtin.systemd_service:
      name: ssh
      state: restarted
      daemon_reload: true
