---
- hosts: ubuntu
  become: true

  tasks:

  - name: Instalar paquetes para autofs
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    loop:
      - autofs
      - python3
      - nfs-common

  - name: Copiar archivo de autofs en etc
    ansible.builtin.copy:
      src: ../files/nfs.autofs
      dest: /etc/auto.master.d/nfs.autofs
      owner: root
      mode: '0644'
    notify: Reiniciar autofs

  - name: Copiar archivo de montaje en etc
    ansible.builtin.copy:
      src: ../files/auto.nfs
      dest: /etc/auto.nfs
      owner: root
      mode: '0644'
    notify: Reiniciar autofs

  - name: Iniciar servicio autofs
    ansible.builtin.systemd_service:
      name: autofs
      state: started
      enabled: true

  handlers:

  - name: Reiniciar autofs
    ansible.builtin.systemd_service:
      name: autofs
      state: restarted
