---
- hosts: ubuntu
  become: true

  tasks:

  - name: Habilitar trafico saliente
    community.general.ufw:
      policy: allow
      direction: outgoing

  - name: Denegar trafico entrante
    community.general.ufw:
      policy: deny
      direction: incoming

  - name: Habilitar SSH
    community.general.ufw:
      name: OpenSSH
      rule: allow

  - name: Habilitar Firewall
    community.general.ufw:
      state: enabled
